In [1]:
a = 3
b = 4

c = a + b
print('Nilai c = ', c)

Nilai c =  7


In [2]:
type(c)

int

In [4]:
a = 3.14
b = 4

c = a + b
print('Nilai c = ', c)

Nilai c =  7.140000000000001


In [5]:
type(c)

float

In [6]:
#PR - 1
#Jika persamaan t = xy + z, dengan x = 3, y = 5 dan z = 6. Selesaikan dalam script python? 

In [7]:
#variabel x, y dan z dengan persamaan t = xy + z

def compute_t(x, y, z):
    t = x * y + z
    return t

In [8]:
compute_t(4, 5, 8)

28

In [9]:
#PR - 2
#Koversi Tempratur.
#Ubah nilai Celcius ke Fahreinheit dengan menggunakan fungsi dalam python?

In [10]:
#Numpy

#01_Membuat vektor (1-D Array)
import numpy as np

a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([1, 2, 3.5, 4, 5])

print(a1)
print(a2)


[1 2 3 4 5]
[1.  2.  3.5 4.  5. ]


In [12]:
#02 range
import numpy as np

b = np.arange(0, 10, 2)

print(b)

[0 2 4 6 8]


In [13]:
#03 Array multidimensi (matrix)
import numpy as np
d = np.array( [  (1, 2, 3, 4, 5),  (6, 7, 8, 9, 10) ] )

print(d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [15]:
import numpy as np

e = np.ones( (5, 5))

print(e)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#aritmatika dalam numpy

#Perkalian Matrix

#PR - 3
# a= [1,2,3] [4,5,6]
#b= matrix (np.ones ([3,3]))
#Selesaikan perkalian matrix di atas dengan menggunakan numpy
